### ISSUE TITLE
Turn of the tracking

### ISSUE THREAD

**Issue by Trudko** [TonkWorks/pepper-autocomplete-atom-package#1]
Hi :), I noticed your package is generating unique user id, whats purpose of that and shouldn't there be settings to turn it off?

**Comment by TonkWorks** [comment]
Hi!  The plan is to use the unique user id to give each user more relevant results based on what they have chosen to auto-complete before. (in theory much like google customizes your searches to be more relevant when you are logged in).

But you are right in that it should definitely be optional.  I'll make it a setting in the next release. Thanks for the input!

**Comment by Trudko** [comment]
My pleasure! thanks for quick response.
